__all__ = ['base_unit',
           'ground_unit',
           'water_unit',
           'air_unit',
           'tank',
           'jeep',
           'superjeep',
           'anti_armour',
           'battleship',
           'carrier',
           'artillery',
           'fighter',
           'anti_air',
           'bomber',
           'teleport_unit',
           'warper']
unit_types = {}
